name: TrueChat
version: 1.0.2
author: Dartanman
main: main.dartanman.truechat.Main
commands:
  truechat:
    description: TrueChat base command
    usage: /<command>
    aliases: [tchat, tc]
  clearchat:
    description: ClearChat command
    usage: /<command>
    aliases: [clearc, cc]